import { sql } from "drizzle-orm";
import { index, integer, jsonb, pgTable, text, uniqueIndex } from "drizzle-orm/pg-core";

/**
 * pending_operations — the durable queue backing the DB-as-channel architecture.
 *
 * One row per in-flight operation. Workers (core replicas and node agents) claim
 * pending rows via `SELECT … FOR UPDATE SKIP LOCKED`, run the handler, and write
 * the result back to the same row. The waiting HTTP request polls the row's
 * status and resolves its Promise when the terminal state lands.
 *
 * See `docs/2026-04-08-db-queue-architecture.md` §3 for the design rationale.
 *
 * ── State machine ──────────────────────────────────────────────────────────
 *
 *            enqueue
 *     ┌──────────────────→ pending
 *     │                       │
 *     │                       │ claim (SELECT … FOR UPDATE SKIP LOCKED)
 *     │                       ▼
 *     │ janitor reset     processing
 *     │  (stale > timeout)    │
 *     └───────────────────────┤
 *                             │
 *                             ├── succeeded (result written)
 *                             │
 *                             └── failed (error_message written)
 *
 * Terminal rows are never re-processed. Retries enqueue a new row (or hit an
 * existing one via idempotency_key).
 */
export const pendingOperations = pgTable(
  "pending_operations",
  {
    /** UUID. Generated by the enqueue path. */
    id: text("id").primaryKey(),
    /**
     * Operation type — determines which handler runs the row.
     * Examples: 'instance.create', 'bot.start', 'pool.warm'.
     */
    type: text("type").notNull(),
    /** Opaque request payload — the arguments the handler needs. */
    payload: jsonb("payload").notNull(),
    /**
     * Which worker pool should drain this row.
     * - 'core'   = any core replica's core-worker
     * - '<node>' = that node's agent-worker
     * - NULL     = any worker (unused today, kept for future flexibility)
     */
    target: text("target"),
    /**
     * pending | processing | succeeded | failed
     * Typed as text to keep PGlite-compatible (pg enums create extra DDL).
     */
    status: text("status").notNull().default("pending"),
    /** Result payload written on success. JSON-serialisable. */
    result: jsonb("result"),
    /** Human-readable error message on failure. */
    errorMessage: text("error_message"),
    /** Worker identity that claimed this row (replica id or agent node id). */
    claimedBy: text("claimed_by"),
    /** ISO timestamp when the row transitioned to 'processing'. */
    claimedAt: text("claimed_at"),
    /** ISO timestamp when the row was inserted. */
    enqueuedAt: text("enqueued_at").notNull().default(sql`(now())`),
    /** ISO timestamp when the row reached a terminal state. */
    completedAt: text("completed_at"),
    /**
     * Caller-supplied idempotency key. Second enqueue with the same key
     * short-circuits to the existing row instead of creating a new one.
     */
    idempotencyKey: text("idempotency_key"),
    /**
     * Max seconds a row may sit in 'processing' before the janitor resets
     * it to 'pending'. Default 300s (5 minutes).
     */
    timeoutS: integer("timeout_s").notNull().default(300),
  },
  (table) => [
    // Fast claim path: find pending rows filtered by target.
    index("idx_pending_ops_claim").on(table.target, table.enqueuedAt).where(sql`${table.status} = 'pending'`),
    // Janitor path: find stuck processing rows.
    index("idx_pending_ops_stuck").on(table.claimedAt).where(sql`${table.status} = 'processing'`),
    // Idempotency lookup — unique partial index so double-enqueue collides.
    uniqueIndex("idx_pending_ops_idempotency").on(table.idempotencyKey).where(sql`${table.idempotencyKey} IS NOT NULL`),
  ],
);

export type PendingOperationRow = typeof pendingOperations.$inferSelect;
export type NewPendingOperation = typeof pendingOperations.$inferInsert;
